triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: info
states:
    ask_name:
        component: meya.input_string
        properties:
            text: "What's your first name?"
            output: first_name
            scope: user
    ask_surname:
        component: meya.input_string
        properties:
            text: "What's your last name?"
            output: last_name
            scope: user
    ask_income:
        component: meya.input_string
        properties:
            text: "What's your income?"
            output: income
            scope: user
    thank_you:
        component: meya.text
        properties:
            text: "Thanks {{ user.first_name }} {{ user.last_name }}, you earn {{ user.income }}."